### PR TITLE
Initial packaging

### PR DESCRIPTION
**Pull request by kdeldycke**
Package the bare copy of [`thumbnailer` plugin](https://github.com/getpelican/pelican-plugins/tree/master/thumbnailer) into a independent python package.

Progress:
* [x] `main` branch pushed: https://github.com/pelican-plugins/thumbnailer/branches.
* [x] Add repository description: `Serialize generated HTML to JSON content for use by the Tipue static search jQuery plugin`.

### CODE REVIEW

**Comment by kdeldycke** [comment]
That PR is now in production on my own blog since https://github.com/kdeldycke/kevin-deldycke-blog/commit/428bedf9c8ec866a13dec0695468fa4bc98e2a4b . Everything's work fine.

@justinmayer: this PR is ready to be reviewed and eventually merged! :)

**Comment by justinmayer** [comment]
Will review this as soon as I can. 😅

**Comment by kdeldycke** [comment]
I propose to merge that PR right away: all tests are passing. That way we can have this plugin released as 1.0.0 and move on to other things. Any details and tweaks can be addressed in a following 1.0.1 release.

**Comment by justinmayer** [comment]
It's been a busy month, but I will make time to review this PR by the end of the week.

**Comment by kdeldycke** [comment]
Tests are passing, migration occured a couple of month ago, I guess it's safe to merge into `main`.

**Pull request merged**
